version: '3'

services:
  app:
    image: bundestag-chatbot:latest
    container_name: bundestag-chatbot
    build: .
    stdin_open: true
    tty: true
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
    - "5001:5001"
